### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'bucket_cap_mb'

### ISSUE THREAD

**Issue by pohjie** [kakaobrain/helo_word#3]
Hi, I am running the pre-train section of the code by executing the command 'python train.py --track 1 --train-mode pretrain --model base --ngpu 2'

```
| model transformer, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 60522496 (num. trained: 60522496)
| training on 2 GPUs
| max tokens per GPU = 4000 and max sentences per GPU = None

| WARNING: 1 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[5747045]
| no existing checkpoint found /home/pohjie/beast19/helo_word/track1/ckpt/pretrain-base-lr0.0005-dr0.3/checkpoint_last.pt
```

However, after the following messages above, I encounter this error:
```
Traceback (most recent call last):
  File "/home/pohjie/anaconda3/envs/helo/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq_cli/train.py", line 392, in cli_main
    distributed_main(args.device_id, args)
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq_cli/train.py", line 380, in distributed_main
    main(args, init_distributed=True)
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq_cli/train.py", line 94, in main
    trainer.dummy_train_step([dummy_batch])
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq/trainer.py", line 350, in dummy_train_step
    self.train_step(dummy_batch, dummy_batch=True)
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq/trainer.py", line 163, in train_step
    self.model.train()
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq/trainer.py", line 81, in model
    self.args, self._model,
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq/models/distributed_fairseq_model.py", line 67, in DistributedFairseqModel
    return _DistributedFairseqModel(**init_kwargs)
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq/models/distributed_fairseq_model.py", line 59, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'bucket_cap_mb'
```

May I know how should I go about resolving this? Thank you!

**Comment by yjchoe** [comment]
Hi @pohjie ,

This might have to do with fairseq's distributed training option (`--ddp-backend no_c10d`) missing in some of our preset training commands. 

For now, can you instead try pretraining with `--model copy`, which does contain the distributed training option?

**Comment by pohjie** [comment]
Hi @yjchoe, it's working now thanks so much!
