### ISSUE TITLE
No such file or directory: '/home/helo_word/data/parallel/raw/ABCN.test.bea19.orig'

### ISSUE THREAD

**Issue by pohjie** [kakaobrain/helo_word#4]
Hi @hammouse, I am running preprocess.py. When it reaches step 6-6, I get the mentioned error above.

```
INFO:root:STEP 6-6. wi test
Namespace(cpu=False, data='/home/pohjie/beast19/helo_word/data/language_model/data-bin', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, fpath=None, future_target=False, gen_subset='test', lazy_load=False, log_format=None, log_interval=1000, max_sentences=None, max_tokens=None, memory_efficient_fp16=False, min_loss_scale=0.0001, model_overrides='{}', no_progress_bar=True, num_shards=1, num_workers=4, output_dictionary_size=-1, output_sent=False, past_target=False, path='/home/pohjie/beast19/helo_word/data/language_model/wiki103.pt', quiet=True, raw_text=False, remove_bpe=None, sample_break_mode=None, seed=1, self_target=False, shard_id=0, skip_invalid_size_inputs_valid_test=False, task='language_modeling', tensorboard_logdir='', threshold_loss_scale=None, tokens_per_sample=1024, user_dir=None)
| dictionary: 267744 types
| loading model(s) from /home/pohjie/beast19/helo_word/data/language_model/wiki103.pt
| dictionary: 267744 types
Traceback (most recent call last):
  File "preprocess.py", line 237, in <module>
    maybe_do(fp.WI_TEST_SP_ORI, spell.check, (fp.WI_TEST_ORI, fp.WI_TEST_SP_ORI))
  File "preprocess.py", line 15, in maybe_do
    func(*inputs)
  File "/home/pohjie/beast19/helo_word/gec/spell.py", line 168, in check
    spellcheck(model, fin, fout, speller=speller)
  File "/home/pohjie/beast19/helo_word/gec/spell.py", line 103, in spellcheck
    lines = open(fin, 'r', encoding='utf-8').read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: '/home/pohjie/beast19/helo_word/data/parallel/raw/ABCN.test.bea19.orig'
```

I've tried running the script a few times to ensure that the previous steps have been run correctly- may I know what am I doing wrongly? I've checked the original wi+locness folder and it does not have the mentioned file too.

Thanks!

**Comment by hammouse** [comment]
We added the code to download `ABCN.test.bea19.orig` on STEP 0-5.
However, this code does not work if you have already downloaded WI+LOCNESS.
Please re-download WI+LOCNESS or download `ABCN.test.bea19.orig` from [here](https://www.cl.cam.ac.uk/research/nl/bea2019st/data/ABCN.bea19.test.orig) to `fp.WI_TEST_ORI`.
